import { getToken } from "nice-styles"

export const ButtonTokens = {
  "--button-primary-base-background-color": getToken("foregroundColor").var,
  "--button-primary-base-border-color": getToken("foregroundColor").var,
  "--button-primary-base-foreground-color": "#fff",
  "--button-primary-disabled-background-color": "#ddd",
  "--button-primary-disabled-border-color": "#bbb",
  "--button-primary-disabled-foreground-color": "#888",
  "--button-primary-error-background-color": getToken("foregroundColor", "error").var,
  "--button-primary-error-border-color": getToken("foregroundColor", "error").var,
  "--button-primary-error-foreground-color": "#fff",
  "--button-primary-success-background-color": getToken("foregroundColor", "success").var,
  "--button-primary-success-border-color": getToken("foregroundColor", "success").var,
  "--button-primary-success-foreground-color": "#fff",
  "--button-primary-warning-background-color": getToken("foregroundColor", "warning").var,
  "--button-primary-warning-border-color": getToken("foregroundColor", "warning").var,
  "--button-primary-warning-foreground-color": "#fff",
  "--button-secondary-base-background-color": "transparent",
  "--button-secondary-base-border-color": getToken("foregroundColor").var,
  "--button-secondary-base-foreground-color": getToken("foregroundColor").var,
  "--button-secondary-disabled-background-color": "transparent",
  "--button-secondary-disabled-border-color": "#888",
  "--button-secondary-disabled-foreground-color": "#888",
  "--button-secondary-error-background-color": "transparent",
  "--button-secondary-error-border-color": getToken("foregroundColor", "error").var,
  "--button-secondary-error-foreground-color": getToken("foregroundColor", "error").var,
  "--button-secondary-success-background-color": "transparent",
  "--button-secondary-success-border-color": getToken("foregroundColor", "success").var,
  "--button-secondary-success-foreground-color": getToken("foregroundColor", "success").var,
  "--button-secondary-warning-background-color": "transparent",
  "--button-secondary-warning-border-color": getToken("foregroundColor", "warning").var,
  "--button-secondary-warning-foreground-color": getToken("foregroundColor", "warning").var,
}
